-- 코드를 작성해주세요
SELECT A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE A INNER JOIN ITEM_INFO B ON A.ITEM_ID = B.ITEM_ID
WHERE PARENT_ITEM_ID IN 
(SELECT A.ITEM_ID
FROM ITEM_INFO A INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = 'RARE')
ORDER BY A.ITEM_ID DESC