-- 코드를 작성해주세요

SELECT A.SCORE, B.EMP_NO,B.EMP_NAME,B.POSITION,B.EMAIL
FROM (SELECT EMP_NO,SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1) AS A LEFT JOIN HR_EMPLOYEES AS B ON A.EMP_NO = B.EMP_NO